version: "3.7"

networks:
  vuejx_network:

services:

  gateway_ui:
    build: ./gateway_ui
    image: binhthvuejx/gateway_ui
    container_name: gateway_ui
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./gateway_ui/:/app
    networks:
      - vuejx_network
    ports:
      - "8080:8080"
    expose:
      - 8080
    environment:
      - SERVICE_SECURITY=http://vuejx-core:3000
      - SECREST_KEY=VnVlSlggQmluaHRoIDEyNTQ1ODEyOSBWdWVqcyBWdWV0aWZ5anM=
      - CLUSTER_NODE=2
    restart: on-failure:5
        
  documentation:
    build: ./documentation
    container_name: documentation
    ports:
      - 8801:8801
    expose:
      - 8801
    environment:
      - SERVICE_NAME=documentation
      - HOST=0.0.0.0
      - ./documentation/:/app
    labels: 
      - api_route=/documentation
    command: sh -c "npm install && npm run serve"
    volumes:
      - ./documentation/:/app
    networks:
      - vuejx_network
    